# readout_conf.toml

# Readout configuration

[readouts.cherenkov]
192 = "*"
193 = "*"
194 = "*"
195 = "*"
196 = "*"
197 = "*"
198 = "*"
199 = "*"

[readouts.timing]
200 = [2, 4]

[readouts.tracking]
200 = [3, 5]