"""Theming for the dashboard — one place, one palette.

A 5-colour palette drives both a light and a dark stylesheet:

    coral      FF6B6B   accent + destructive (e.g. Stop button, error state)
    green      0BDA51   success + "things are okay" highlights
    sky        AFDBF5   informational / setting-set banner backgrounds
    warm_grey  9B8E8E   secondary text + subtle borders
    ink        2A2929   primary text on light / page background on dark

Mode selection follows three values:

    ``"system"``  → follow ``QStyleHints.colorScheme()`` and react to
                    its ``colorSchemeChanged`` signal at runtime.
    ``"light"``   → force light.
    ``"dark"``    → force dark.

The widget stylesheets in the rest of the package must NOT hard-code
hex colours — they should query :func:`palette` for everything.
Stylesheets that need to react to the active mode use the QSS
generated by :func:`stylesheet`.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

from PySide6 import QtCore, QtGui, QtWidgets


# ---------------------------------------------------------------------------
# Palette
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Palette:
    """Resolved colour set for one mode (light or dark).

    Names are role-based, not literal — e.g. ``surface`` is the card
    background, not "white" or "grey".  Hex literals are the
    end-points; intermediate tones come from ``mix`` at render time.
    """

    # Brand five.
    coral: str = "#FF6B6B"
    green: str = "#0BDA51"
    sky: str = "#AFDBF5"
    warm_grey: str = "#9B8E8E"
    ink: str = "#2A2929"

    # Derived roles — overridden per mode.
    bg: str = "#FAFAFB"          # window background
    surface: str = "#FFFFFF"     # card / form background
    surface_alt: str = "#F1F3F6"  # subtle striping for nested rows
    border: str = "#D6D9DE"
    text: str = "#2A2929"
    text_muted: str = "#6B6968"
    accent: str = "#FF6B6B"      # primary highlight (coral)
    accent_text: str = "#FFFFFF"
    info: str = "#AFDBF5"
    success: str = "#0BDA51"
    warning: str = "#E0A40A"
    danger: str = "#FF6B6B"


def light_palette() -> Palette:
    return Palette(
        bg="#FAFAFB",
        surface="#FFFFFF",
        surface_alt="#F1F3F6",
        border="#D6D9DE",
        text="#2A2929",
        text_muted="#6B6968",
        accent="#FF6B6B",
        accent_text="#FFFFFF",
    )


def dark_palette() -> Palette:
    # Same brand colours, different surfaces.  Ink becomes the page
    # background; surfaces are slightly lifted off it so cards still
    # read as "raised".  Text uses a warm off-white so the warm-grey
    # accent stays visually anchored.
    return Palette(
        bg="#1B1A1A",
        surface="#2A2929",
        surface_alt="#33312F",
        border="#46423F",
        text="#F2EFEC",
        text_muted="#B8B0AA",
        accent="#FF6B6B",
        accent_text="#1B1A1A",
        warning="#F0C44A",
    )


# ---------------------------------------------------------------------------
# Mode + stylesheet
# ---------------------------------------------------------------------------


class Mode(str, Enum):
    SYSTEM = "system"
    LIGHT = "light"
    DARK = "dark"


def resolve_mode(mode: Mode | str) -> tuple[bool, Mode]:
    """Return ``(is_dark, effective_mode)``.

    ``"system"`` is collapsed to ``"light"`` or ``"dark"`` by asking
    Qt for the current ``colorScheme()``; the second element of the
    tuple records the resolved mode so callers can re-display it.
    """
    m = Mode(mode) if not isinstance(mode, Mode) else mode
    if m == Mode.LIGHT:
        return False, Mode.LIGHT
    if m == Mode.DARK:
        return True, Mode.DARK
    # SYSTEM — ask Qt.
    scheme = QtGui.QGuiApplication.styleHints().colorScheme()
    is_dark = scheme == QtCore.Qt.ColorScheme.Dark
    return is_dark, Mode.SYSTEM


def palette(mode: Mode | str = Mode.SYSTEM) -> Palette:
    """Resolved palette for ``mode``."""
    is_dark, _ = resolve_mode(mode)
    return dark_palette() if is_dark else light_palette()


def stylesheet(mode: Mode | str = Mode.SYSTEM) -> str:
    """Generate the global QSS for ``mode``.

    Covers the widgets used across the panel (tab bar, list widgets,
    form labels, push buttons, frames, line edits, spinboxes, group
    boxes).  Widget-specific stylesheets in the rest of the package
    are expected to either be removed (defer to the global QSS) or
    use ``objectName`` selectors that the QSS targets.
    """
    p = palette(mode)
    is_dark, _ = resolve_mode(mode)
    # Selection colour (slightly stronger than the surface_alt so it
    # reads as "active" even in dark mode where contrast is tight).
    select_bg = p.accent
    select_fg = p.accent_text

    return f"""
    QMainWindow, QWidget {{
        background: {p.bg};
        color: {p.text};
    }}
    QTabWidget::pane {{
        border: 1px solid {p.border};
        background: {p.surface};
    }}
    QTabBar::tab {{
        background: {p.bg};
        color: {p.text_muted};
        padding: 6px 14px;
        border: 1px solid transparent;
        border-bottom: none;
    }}
    QTabBar::tab:selected {{
        background: {p.surface};
        color: {p.text};
        border: 1px solid {p.border};
        border-bottom-color: {p.surface};
    }}
    QTabBar::tab:hover:!selected {{
        color: {p.text};
    }}

    QLabel {{ background: transparent; }}

    QListWidget, QTableView, QTreeView, QPlainTextEdit, QTextEdit {{
        background: {p.surface};
        color: {p.text};
        border: 1px solid {p.border};
        selection-background-color: {select_bg};
        selection-color: {select_fg};
    }}
    QListWidget::item:hover {{ background: {p.surface_alt}; }}
    QListWidget::item:selected {{ background: {select_bg}; color: {select_fg}; }}

    QHeaderView::section {{
        background: {p.surface_alt};
        color: {p.text};
        border: none;
        border-right: 1px solid {p.border};
        padding: 4px 6px;
    }}

    QLineEdit, QSpinBox, QDoubleSpinBox, QComboBox {{
        background: {p.surface};
        color: {p.text};
        border: 1px solid {p.border};
        border-radius: 3px;
        padding: 2px 4px;
        selection-background-color: {select_bg};
        selection-color: {select_fg};
    }}
    QLineEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus, QComboBox:focus {{
        border-color: {p.accent};
    }}
    QComboBox QAbstractItemView {{
        background: {p.surface};
        color: {p.text};
        selection-background-color: {select_bg};
        selection-color: {select_fg};
    }}

    QPushButton {{
        background: {p.surface_alt};
        color: {p.text};
        border: 1px solid {p.border};
        border-radius: 3px;
        padding: 4px 10px;
    }}
    QPushButton:hover {{ background: {_mix(p.surface_alt, p.text, 0.06)}; }}
    QPushButton:pressed {{ background: {_mix(p.surface_alt, p.text, 0.12)}; }}
    QPushButton:disabled {{
        background: {p.surface};
        color: {p.text_muted};
        border-color: {p.surface_alt};
    }}

    QToolButton {{
        background: transparent;
        color: {p.text};
        border: none;
        padding: 2px 4px;
    }}
    QToolButton:hover {{ background: {p.surface_alt}; }}

    QGroupBox {{
        background: {p.surface};
        color: {p.text};
        border: 1px solid {p.border};
        border-radius: 4px;
        margin-top: 12px;
        padding-top: 8px;
    }}
    QGroupBox::title {{
        subcontrol-origin: margin;
        subcontrol-position: top left;
        padding: 0 6px;
        color: {p.text};
    }}

    QStatusBar {{ background: {p.bg}; color: {p.text_muted}; }}
    QScrollBar:vertical {{
        background: {p.bg}; width: 12px; margin: 0; border: none;
    }}
    QScrollBar::handle:vertical {{
        background: {p.surface_alt};
        min-height: 24px;
        border-radius: 6px;
    }}
    QScrollBar::handle:vertical:hover {{ background: {_mix(p.surface_alt, p.text, 0.15)}; }}
    QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{
        background: none; border: none; height: 0;
    }}

    /* Object-name selectors used by widget code to opt into specific
       roles without hard-coding hex colours. */
    QFrame#cardSurface {{
        background: {p.surface};
        border: 1px solid {p.border};
        border-radius: 6px;
    }}
    QFrame#infoBanner {{
        background: {_mix(p.info, p.bg, 0.6)};
        border: 1px solid {p.info};
        border-radius: 4px;
    }}
    QFrame#warnBanner {{
        background: {_mix(p.warning, p.bg, 0.75)};
        border: 1px solid {p.warning};
        border-radius: 4px;
    }}
    QFrame#errorBanner {{
        background: {_mix(p.danger, p.bg, 0.75)};
        border: 1px solid {p.danger};
        border-radius: 4px;
    }}
    QLabel#muted {{ color: {p.text_muted}; }}
    QLabel#sectionTitle {{ color: {p.text}; font-weight: 600; }}
    QPushButton#dangerButton {{
        background: {p.danger}; color: {p.accent_text}; border: 1px solid {p.danger};
    }}
    QPushButton#dangerButton:disabled {{
        background: {p.surface}; color: {p.text_muted}; border-color: {p.surface_alt};
    }}
    """


def apply(app: QtWidgets.QApplication, mode: Mode | str = Mode.SYSTEM) -> Palette:
    """Apply the resolved stylesheet to ``app``; return the palette used."""
    app.setStyleSheet(stylesheet(mode))
    return palette(mode)


# ---------------------------------------------------------------------------
# Misc
# ---------------------------------------------------------------------------


def _mix(a_hex: str, b_hex: str, t: float) -> str:
    """Linear blend ``a → b`` with ``t ∈ [0, 1]``; both ``"#RRGGBB"``.

    Used inside QSS-generation only (cheap, no Qt objects).  ``t = 0``
    → pure ``a``; ``t = 1`` → pure ``b``.
    """
    a = QtGui.QColor(a_hex)
    b = QtGui.QColor(b_hex)
    t = max(0.0, min(1.0, float(t)))
    return QtGui.QColor(
        int(a.red() * (1 - t) + b.red() * t),
        int(a.green() * (1 - t) + b.green() * t),
        int(a.blue() * (1 - t) + b.blue() * t),
    ).name()


__all__ = [
    "Mode",
    "Palette",
    "apply",
    "dark_palette",
    "light_palette",
    "palette",
    "resolve_mode",
    "stylesheet",
]
